test_get_nb_char (__main__.TestExercice) ... ok
test_get_nb_words (__main__.TestExercice) ... ERROR
test_pair (__main__.TestExercice) ... ok
test_remove_third_char (__main__.TestExercice) ... ok
test_replace_char (__main__.TestExercice) ... ok

======================================================================
ERROR: test_get_nb_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jeanj\OneDrive - polymtl.ca\Automne 2021\INF1007\Cours 4 Exo\c03_ch4_exercices-SenecalJF\test_exercice.py", line 75, in test_get_nb_words
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
  File "c:\Users\jeanj\OneDrive - polymtl.ca\Automne 2021\INF1007\Cours 4 Exo\c03_ch4_exercices-SenecalJF\test_exercice.py", line 75, in <listcomp>
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
TypeError: get_nb_words() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
